# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: ~, prefer_extension: true }
            - { path: '^/admin', priorities: ['html'], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: ['json', 'html', '*/*'], fallback_format: json, prefer_extension: true }